// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAHmsvDwqBaLSzh-4_r4R6Smz3Lk67s1s',
    appId: '1:509839740929:web:e1348d6d795eae23fcb000',
    messagingSenderId: '509839740929',
    projectId: 'post-scheduler-97f47',
    authDomain: 'post-scheduler-97f47.firebaseapp.com',
    storageBucket: 'post-scheduler-97f47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDubusEIUuQzTGfdng6J64_rVoE8XC8P28',
    appId: '1:509839740929:android:2f6280f2a871589afcb000',
    messagingSenderId: '509839740929',
    projectId: 'post-scheduler-97f47',
    storageBucket: 'post-scheduler-97f47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwjyoQBeQ4rlIulYukJ79d3XP7J3LwcRY',
    appId: '1:509839740929:ios:ab959dc6e9f2f84efcb000',
    messagingSenderId: '509839740929',
    projectId: 'post-scheduler-97f47',
    storageBucket: 'post-scheduler-97f47.appspot.com',
    iosBundleId: 'com.example.postScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwjyoQBeQ4rlIulYukJ79d3XP7J3LwcRY',
    appId: '1:509839740929:ios:ab959dc6e9f2f84efcb000',
    messagingSenderId: '509839740929',
    projectId: 'post-scheduler-97f47',
    storageBucket: 'post-scheduler-97f47.appspot.com',
    iosBundleId: 'com.example.postScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAHmsvDwqBaLSzh-4_r4R6Smz3Lk67s1s',
    appId: '1:509839740929:web:e91a7402679259a2fcb000',
    messagingSenderId: '509839740929',
    projectId: 'post-scheduler-97f47',
    authDomain: 'post-scheduler-97f47.firebaseapp.com',
    storageBucket: 'post-scheduler-97f47.appspot.com',
  );
}
